### ISSUE TITLE
Yet Another Issue

### ISSUE THREAD

**Issue by pl608** [oversword/robot#1]
dont know if it was me or not but here it is:
![image](https://user-images.githubusercontent.com/78400949/156847284-a5a8a768-9a16-4809-8f62-60c3235c9e92.png)
I was attempting to place the robot on dirt after I had just "dug" one up.
also, can you put a table with all the robots commands?(not the ability commands since those are already in there)

**Comment by oversword** [comment]
@pl608 

Thanks, I'll fix this.

The only command that's not in the abilities is `robot.stop()`

**Comment by oversword** [comment]
@pl608 that should be fixed, pull the latest and try again. Thanks for testing this out!
